/********************************************************************
* ./src/WCLRootDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ./src/WCLRootDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableWCLRootDict();
extern void G__cpp_setup_inheritanceWCLRootDict();
extern void G__cpp_setup_typetableWCLRootDict();
extern void G__cpp_setup_memvarWCLRootDict();
extern void G__cpp_setup_globalWCLRootDict();
extern void G__cpp_setup_memfuncWCLRootDict();
extern void G__cpp_setup_funcWCLRootDict();
extern void G__set_cpp_environmentWCLRootDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "WCSimRecoObjectTable.hh"
#include "WCSimRecoDigit.hh"
#include "SandBoxPMTcoverage.hh"
#include "WCSimTrueLight.hh"
#include "WCSimTruePart.hh"
#include "WCSimTrueCapture.hh"
#include "WCLTreeReader.hh"
#include "WCLTreeWriter.hh"
#include "WChRecoLite.hh"
#include "HighEReco.hh"
#include "LowEReco.hh"
#include "LikelihoodGenerator.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__WCLRootDictLN_TClass;
extern G__linked_taginfo G__WCLRootDictLN_TBuffer;
extern G__linked_taginfo G__WCLRootDictLN_TMemberInspector;
extern G__linked_taginfo G__WCLRootDictLN_TObject;
extern G__linked_taginfo G__WCLRootDictLN_TString;
extern G__linked_taginfo G__WCLRootDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__WCLRootDictLN_basic_fstreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__WCLRootDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__WCLRootDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__WCLRootDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__WCLRootDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__WCLRootDictLN_WCSimRecoObjectTable;
extern G__linked_taginfo G__WCLRootDictLN_WCSimRecoDigit;
extern G__linked_taginfo G__WCLRootDictLN_SandBoxPMTcoverage;
extern G__linked_taginfo G__WCLRootDictLN_WCSimTrueLight;
extern G__linked_taginfo G__WCLRootDictLN_WCSimTruePart;
extern G__linked_taginfo G__WCLRootDictLN_WCSimTrueCapture;
extern G__linked_taginfo G__WCLRootDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__WCLRootDictLN_TTree;
extern G__linked_taginfo G__WCLRootDictLN_TFile;
extern G__linked_taginfo G__WCLRootDictLN_TBranch;
extern G__linked_taginfo G__WCLRootDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__WCLRootDictLN_TChain;
extern G__linked_taginfo G__WCLRootDictLN_WCLTreeReader;
extern G__linked_taginfo G__WCLRootDictLN_WCLTreeWriter;
extern G__linked_taginfo G__WCLRootDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__WCLRootDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__WCLRootDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__WCLRootDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__WCLRootDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__WCLRootDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__WCLRootDictLN_TElementActionTlEdoublegR;
extern G__linked_taginfo G__WCLRootDictLN_TElementPosActionTlEdoublegR;
extern G__linked_taginfo G__WCLRootDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__WCLRootDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__WCLRootDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__WCLRootDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__WCLRootDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__WCLRootDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__WCLRootDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__WCLRootDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__WCLRootDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__WCLRootDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__WCLRootDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__WCLRootDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__WCLRootDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__WCLRootDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__WCLRootDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__WCLRootDictLN_TMatrixTlEdoublegR;
extern G__linked_taginfo G__WCLRootDictLN_TMatrixTRow_constlEdoublegR;
extern G__linked_taginfo G__WCLRootDictLN_TMatrixTRowlEdoublegR;
extern G__linked_taginfo G__WCLRootDictLN_TMatrixTDiag_constlEdoublegR;
extern G__linked_taginfo G__WCLRootDictLN_TMatrixTColumn_constlEdoublegR;
extern G__linked_taginfo G__WCLRootDictLN_TMatrixTFlat_constlEdoublegR;
extern G__linked_taginfo G__WCLRootDictLN_TMatrixTSub_constlEdoublegR;
extern G__linked_taginfo G__WCLRootDictLN_TMatrixTSparseRow_constlEdoublegR;
extern G__linked_taginfo G__WCLRootDictLN_TMatrixTSparseDiag_constlEdoublegR;
extern G__linked_taginfo G__WCLRootDictLN_TMatrixTColumnlEdoublegR;
extern G__linked_taginfo G__WCLRootDictLN_TMatrixTDiaglEdoublegR;
extern G__linked_taginfo G__WCLRootDictLN_TMatrixTFlatlEdoublegR;
extern G__linked_taginfo G__WCLRootDictLN_TMatrixTSublEdoublegR;
extern G__linked_taginfo G__WCLRootDictLN_TMatrixTSparseRowlEdoublegR;
extern G__linked_taginfo G__WCLRootDictLN_TMatrixTSparseDiaglEdoublegR;
extern G__linked_taginfo G__WCLRootDictLN_TRandom;
extern G__linked_taginfo G__WCLRootDictLN_WChRecoLite;
extern G__linked_taginfo G__WCLRootDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__WCLRootDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__WCLRootDictLN_maplEintcOdoublecOlesslEintgRcOallocatorlEpairlEconstsPintcOdoublegRsPgRsPgR;
extern G__linked_taginfo G__WCLRootDictLN_TH2D;
extern G__linked_taginfo G__WCLRootDictLN_TH3D;
extern G__linked_taginfo G__WCLRootDictLN_HighEReco;
extern G__linked_taginfo G__WCLRootDictLN_LowEReco;
extern G__linked_taginfo G__WCLRootDictLN_LikelihoodGenerator;

/* STUB derived class for protected member access */
